[project]
name = "simple-schema"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Robert Sherwood", email = "robert.sherwood@credentive.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
simple-schema = "simple_schema:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
